// <auto-generated />
// GlobalUsings for TiXL Core module - reduces clutter and improves readability

// Core TiXL components
global using TiXL;
global using TiXL.Core;
global using TiXL.Core.AudioVisual;
global using TiXL.Core.Graphics;
global using TiXL.Core.Graphics.DirectX12;
global using TiXL.Core.Graphics.PSO;
global using TiXL.Core.IO;
global using TiXL.Core.Logging;
global using TiXL.Core.NodeGraph;
global using TiXL.Core.Operators;
global using TiXL.Core.Performance;

// DirectX and Graphics
global using Vortice;
global using Vortice.Direct3D;
global using Vortice.Direct3D12;
global using Vortice.DXGI;
global using Vortice.Mathematics;

// Mathematics and Numeric types
global using System.Numerics;

// Threading and Concurrency
global using System.Threading;
global using System.Threading.Tasks;
global using System.Threading.Channels;
global using System.Threading.Tasks.Dataflow;
global using System.Collections.Concurrent;
global using System.Collections.Frozen;

// Performance and Diagnostics
global using System.Diagnostics;
global using System.Diagnostics.Tracing;

// Memory and Span types
global using System;
global using System.Span;
global using System.ReadOnlySpan;
global using System.Memory;
global using System.ReadOnlyMemory;
global using System.Buffers;

// Logging
global using Microsoft.Extensions.Logging;
global using Serilog;

// IO and File System
global using System.IO;
global using System.IO.Pipes;
global using System.IO.MemoryMappedFiles;

// Collections
global using System.Collections;
global using System.Collections.Generic;

// Exception handling
global using System.ComponentModel;

// Validation and Debugging
global using System.Diagnostics.CodeAnalysis;

// Task-based async patterns
global using System.Runtime.CompilerServices;

// Graphics-specific utilities
global using TiXL.Common;
global using TiXL.Common.Mathematics;
global using TiXL.Common.Threading;
global using TiXL.Common.Diagnostics;

// GPU resource management
global using TiXL.Gpu;
global using TiXL.Gpu.Resources;
global using TiXL.Gpu.Shaders;

// Performance monitoring
global using TiXL.Performance;
global using TiXL.Performance.Counters;

// Error handling
global using TiXL.Diagnostics;
