#!/usr/bin/env pwsh

param(
    [string]$ProjectPath = ".",
    [switch]$Interactive
)

Write-Host "🛡️  TiXL Security Scanning Setup" -ForegroundColor Green
Write-Host "=================================" -ForegroundColor Green

# Check if running in Git repository
$gitStatus = git status 2>$null
if (-not $gitStatus) {
    Write-Host "⚠️  Not in a Git repository. Please run from the project root." -ForegroundColor Yellow
    exit 1
}

# Check if .NET project exists
$csprojFiles = Get-ChildItem -Path $ProjectPath -Filter "*.csproj" -Recurse
if ($csprojFiles.Count -eq 0) {
    Write-Host "⚠️  No .csproj files found in project." -ForegroundColor Yellow
    exit 1
}

Write-Host "Found $($csprojFiles.Count) .NET project files" -ForegroundColor Green

# Create necessary directories
$directories = @(
    ".github/workflows",
    ".github/codeql",
    "scripts",
    "tools"
)

foreach ($dir in $directories) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "Created directory: $dir" -ForegroundColor Blue
    }
}

# Install global tools
Write-Host "`n🔧 Installing global .NET tools..." -ForegroundColor Yellow

$tools = @(
    @{ Name = "dotnet-retire"; Version = "3.1.0"; Description = "Vulnerability scanner for .NET" },
    @{ Name = "dotnet-reportgenerator-globaltool"; Version = "5.2.0"; Description = "Report generator for test coverage" }
)

foreach ($tool in $tools) {
    try {
        Write-Host "Installing $($tool.Name)..." -ForegroundColor Blue
        $installArgs = @("tool", "install", "--global", $tool.Name)
        if ($tool.Version) {
            $installArgs += "--version", $tool.Version
        }
        & dotnet @installArgs | Out-Null
        Write-Host "✅ $($tool.Name) installed successfully" -ForegroundColor Green
    } catch {
        Write-Host "❌ Failed to install $($tool.Name): $_" -ForegroundColor Red
    }
}

# Install pre-commit hooks if requested
if ($Interactive -or (Read-Host "Install pre-commit hooks? (y/N)" | Select-String -Pattern "^[Yy]")) {
    if (Get-Command pip -ErrorAction SilentlyContinue) {
        pip install pre-commit
        Write-Host "Installing pre-commit hooks..." -ForegroundColor Blue
        pre-commit install
        Write-Host "✅ Pre-commit hooks installed" -ForegroundColor Green
    } else {
        Write-Host "⚠️  pip not found. Please install pre-commit manually." -ForegroundColor Yellow
    }
}

# Create security monitoring script
$securityScanScript = @'
#!/usr/bin/env pwsh

param(
    [switch]$Verbose,
    [switch]$FailOnWarning,
    [string]$OutputPath = "security-report.json"
)

Write-Host "🔍 Starting TiXL Security Scan..." -ForegroundColor Green

# NuGet Audit
try {
    Write-Host "Running NuGet audit..." -ForegroundColor Blue
    dotnet restore --verbosity quiet
    dotnet list package --vulnerable --include-transitive
    Write-Host "✅ NuGet audit passed" -ForegroundColor Green
} catch {
    Write-Host "❌ NuGet audit failed: $_" -ForegroundColor Red
    if ($FailOnWarning) { exit 1 }
}

# dotnet-retire
try {
    Write-Host "Running dotnet-retire..." -ForegroundColor Blue
    dotnet retire --ignore-urls "https://localhost/**"
    Write-Host "✅ dotnet-retire scan passed" -ForegroundColor Green
} catch {
    Write-Host "❌ dotnet-retire scan failed: $_" -ForegroundColor Red
    if ($FailOnWarning) { exit 1 }
}

Write-Host "🛡️ All security scans passed!" -ForegroundColor Green
'@

$securityScanScript | Out-File -FilePath "scripts/security-scan.ps1" -Encoding UTF8
Write-Host "Created security scan script: scripts/security-scan.ps1" -ForegroundColor Blue

# Create README for security setup
$readmeContent = @"
# TiXL Security Scanning Setup

This directory contains security scanning tools and configurations for the TiXL project.

## Quick Start

1. **Run Security Scan:**
   ```powershell
   .\scripts\security-scan.ps1
   ```

2. **Setup for Development:**
   ```powershell
   .\scripts\security-setup.ps1 -Interactive
   ```

3. **GitHub Actions:**
   - Security scans run automatically on push/PR
   - Check the Actions tab for scan results

## Tools Included

- **NuGet Audit**: Built-in package vulnerability scanning
- **dotnet-retire**: Known .NET CVE scanner
- **CodeQL**: Static code analysis
- **OWASP Dependency Check**: Third-party vulnerability scanning
- **GitHub Security Advisories**: Automatic vulnerability detection

## Monitoring

- Weekly dependency updates (Mondays at 4 AM UTC)
- Daily security scans (2 AM UTC)
- Real-time PR security validation

## Support

For issues with security scanning:
1. Check the security scan results in GitHub Actions
2. Review the security report generated by the scan script
3. Create an issue with the 'security' label

---
Generated on: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@

$readmeContent | Out-File -FilePath "scripts/README.md" -Encoding UTF8

Write-Host "`n✅ Security setup completed!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Review the generated GitHub workflows in .github/workflows/" -ForegroundColor White
Write-Host "2. Enable GitHub Security Advisories in your repository settings" -ForegroundColor White
Write-Host "3. Configure Dependabot for automated dependency updates" -ForegroundColor White
Write-Host "4. Run './scripts/security-scan.ps1' to test the setup" -ForegroundColor White
Write-Host ""
Write-Host "For detailed configuration, see docs/security_scanning_setup.md" -ForegroundColor Yellow