// <auto-generated />
// This file contains global using directives that reduce code clutter
// GlobalUsings are automatically imported for all C# files in the project

// Core TiXL namespaces
global using TiXL.Core;
global using TiXL.Core.AudioVisual;
global using TiXL.Core.Graphics;
global using TiXL.Core.Graphics.DirectX12;
global using TiXL.Core.Graphics.PSO;
global using TiXL.Core.IO;
global using TiXL.Core.Logging;
global using TiXL.Core.NodeGraph;
global using TiXL.Core.Operators;
global using TiXL.Core.Performance;

// .NET System namespaces
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.Specialized;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Linq;
global using System.Numerics;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;

// Task-based async patterns
global using System.Threading.Tasks.Dataflow;

// Collections and data structures
global using System.Collections.Concurrent;
global using System.Collections.Frozen;
global using System.Collections.Immutable;

// Graphics and DirectX
global using Vortice;
global using Vortice.Direct3D;
global using Vortice.Direct3D12;
global using Vortice.DXGI;
global using Vortice.Mathematics;
global using Vortice.Windows;

// Audio and Media
global using Vortice.XAudio2;
global using Vortice.MediaFoundation;

// Interop and P/Invoke
global using Microsoft.Win32.SafeHandles;
global using Microsoft.Win32;

// Diagnostics and Performance
global using System.Diagnostics.Tracing;
global using System.Diagnostics.PerformanceCounter;

// Threading and Concurrency
global using System.Threading.Channels;
global using System.Threading.RateLimiting;

// IO and File System
global using System.IO.Pipes;
global using System.IO.MemoryMappedFiles;

// Text Processing
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.Json.Serialization.Metadata;
global using System.Text.RegularExpressions;

// Security and Cryptography
global using System.Security.Cryptography;
global using System.Security.Cryptography.Algorithms;
global using System.Security.Cryptography.X509Certificates;

// Networking and HTTP
global using System.Net;
global using System.Net.Http;
global using System.Net.Http.Json;
global using Microsoft.Extensions.Http;

// Extension methods and Utilities
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Options.ConfigurationExtensions;

// Logging Abstractions
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Logging.Configuration;
global using Microsoft.Extensions.Logging.Console;
global using Microsoft.Extensions.Logging.Debug;

// Testing and Validation
global using Xunit;
global using Xunit.Abstractions;
global using FluentAssertions;
global using FluentAssertions.Collections;
global using FluentAssertions.Execution;
global using FluentAssertions.Equivalency;
global using FluentAssertions.Types;
global using FluentAssertions.Primitives;
global using FluentAssertions.Common;
global using Moq;
global using Moq.Language;
global using Moq.Language.Flow;

// Configuration and Options
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.DependencyInjection;

// Benchmarking
global using BenchmarkDotNet;
global using BenchmarkDotNet.Attributes;
global using BenchmarkDotNet.Engines;
global using BenchmarkDotNet.Jobs;
global using BenchmarkDotNet.Environments;
global using BenchmarkDotNet.Mathematics;
global using BenchmarkDotNet.Running;
global using BenchmarkDotNet.Columns;
global using BenchmarkDotNet.Reports;
global using BenchmarkDotNet.Horology;
global using BenchmarkDotNet.Configurations;
global using BenchmarkDotNet.Exporters;

// Data Serialization
global using System.Text.Json.Serialization;

// JSON Processing
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.Json.Serialization.Metadata;

// Value Tuples and Pattern Matching
global using System.Runtime.InteropServices;

// Memory and Performance
global using System.Buffers;
global using System.Memory;
global using System.Runtime.Intrinsics;

// Logging Enhancement
global using Serilog;
global using Serilog.Events;
global using Serilog.Formatting;
global using Serilog.Formatting.Display;
global using Serilog.Configuration;
global using Serilog.Extensions.Hosting;
global using Serilog.Extensions.Logging;
global using Serilog.Settings.Configuration;
global using Serilog.Sinks.Console;
global using Serilog.Sinks.File;

// WPF and WinUI (for Editor components)
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Media;

// Dependency Injection and Service Registration
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;

// Task-based programming patterns
global using System.Runtime.CompilerServices;
global using System.Collections.Generic.Extensions;

// Unsafe operations for performance-critical code
global using System.Runtime.CompilerServices;

// Time-related types
global using System.DateOnly;
global using System.TimeOnly;

// Span and Memory types for high-performance scenarios
global using System.Span;
global using System.ReadOnlySpan;
global using System.Memory;
global using System.ReadOnlyMemory;

// Generic math operations (C# 11+)
global using System.Numerics;

// Parameter validation
global using System.Diagnostics.CodeAnalysis;

// Record structs and patterns
global using System.Runtime.CompilerServices;

// Generic interfaces and patterns
global using System.Runtime.InteropServices;

// Async programming enhancements
global using System.Threading.Tasks;

// Explicit null reference type annotations
global using System.Diagnostics.CodeAnalysis;

// Pattern matching enhancements
global using System.Runtime.CompilerServices;

// Collection expressions and improvements
global using System.Collections.Generic;

// Value-based programming patterns
global using System.Runtime.CompilerServices;

// Performance-focused types
global using System.Buffers;
global using System.Memory;

// File I/O enhancements
global using System.IO;

// Memory-mapped files for large data processing
global using System.IO.MemoryMappedFiles;

// Named pipes for inter-process communication
global using System.IO.Pipes;

// Performance counters and monitoring
global using System.Diagnostics.PerformanceCounter;

// Configuration and settings
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Configuration.Binder;
global using Microsoft.Extensions.Configuration.CommandLine;
global using Microsoft.Extensions.Configuration.EnvironmentVariables;
global using Microsoft.Extensions.Configuration.Json;
global using Microsoft.Extensions.Configuration.UserSecrets;
global using Microsoft.Extensions.Configuration.Xml;

// Host and application lifecycle
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Hosting.Abstractions;
global using Microsoft.Extensions.Hosting.Internal;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Options.ConfigurationExtensions;
global using Microsoft.Extensions.Options.DataAnnotations;
global using Microsoft.Extensions.Primitives;

// Event handlers and delegates
global using System.ComponentModel;

// Optional pattern for null checks
global using System;

// Exception handling utilities
global using System.ComponentModel;

// Data validation
global using System.ComponentModel.DataAnnotations;

// Graphics utilities and common structures
global using TiXL.Common;
global using TiXL.Common.Mathematics;
global using TiXL.Common.Threading;
global using TiXL.Common.Collections;
global using TiXL.Common.Collections.LockFree;
global using TiXL.Common.Diagnostics;

// Event handling and patterns
global using TiXL.Common.Events;
global using TiXL.Common.Messaging;

// Performance monitoring
global using TiXL.Common.Diagnostics.Performance;

// Resource management
global using TiXL.Common.IO;
global using TiXL.Common.IO.FileSystem;
global using TiXL.Common.IO.Serialization;

// Utility classes
global using TiXL.Common.Validation;
global using TiXL.Common.Converters;

// Math and numeric utilities
global using TiXL.Mathematics.Vectors;
global using TiXL.Mathematics.Matrices;
global using TiXL.Mathematics.Geometry;
global using TiXL.Mathematics.Random;

// Audio processing utilities
global using TiXL.Audio;
global using TiXL.Audio.Processing;
global using TiXL.Audio.Analysis;

// Video and image processing
global using TiXL.Graphics;
global using TiXL.Graphics.Rendering;
global using TiXL.Graphics.Shaders;
global using TiXL.Graphics.Effects;

// Node graph system
global using TiXL.NodeGraph;
global using TiXL.NodeGraph.Core;
global using TiXL.NodeGraph.Nodes;
global using TiXL.NodeGraph.Connections;
global using TiXL.NodeGraph.Evaluation;

// Operator system
global using TiXL.Operators;
global using TiXL.Operators.Core;
global using TiXL.Operators.Graphics;
global using TiXL.Operators.Audio;
global using TiXL.Operators.Mathematics;
global using TiXL.Operators.Control;

// Logging infrastructure
global using TiXL.Logging;
global using TiXL.Logging.Core;
global using TiXL.Logging.Outputs;
global using TiXL.Logging.Formatters;

// Performance monitoring
global using TiXL.Performance;
global using TiXL.Performance.Counters;
global using TiXL.Performance.Profilers;
global using TiXL.Performance.Benchmarks;

// File I/O operations
global using TiXL.IO;
global using TiXL.IO.Files;
global using TiXL.IO.Streams;
global using TiXL.IO.Buffers;

// GPU resource management
global using TiXL.Gpu;
global using TiXL.Gpu.Resources;
global using TiXL.Gpu.Shaders;
global using TiXL.Gpu.Textures;
global using TiXL.Gpu.Buffers;

// Error handling and diagnostics
global using TiXL.Diagnostics;
global using TiXL.Diagnostics.Logging;
global using TiXL.Diagnostics.Exceptions;
global using TiXL.Diagnostics.Debugging;
